"""Type stubs for the icao_shared_kernel native extension.

Hand-written, not generated — see task 0015-python-support-plan.md for why.
Keep in sync with src/lib.rs and the per-type src/*.rs modules by hand.
"""

from datetime import datetime

class ValidationError(ValueError):
    """Base class for every icao_shared_kernel validation error."""

class WaypointLengthError(ValidationError): ...
class WaypointCharsetError(ValidationError): ...
class InvalidAircraftTypeError(ValidationError): ...
class FieldLengthError(ValidationError): ...
class EmptyFieldError(ValidationError): ...
class IssuingStateError(ValidationError): ...
class LatitudeError(ValidationError): ...
class LongitudeError(ValidationError): ...

def validate_waypoint_code(code: str) -> None:
    """Validate a waypoint designator without constructing a Waypoint."""

class Waypoint:
    def __init__(self, designator: str) -> None: ...
    @property
    def designator(self) -> str: ...

class Coordinate:
    def __init__(self, latitude: str, longitude: str) -> None: ...
    @property
    def latitude(self) -> str: ...
    @property
    def longitude(self) -> str: ...

class SignificantPoint:
    class Designator(SignificantPoint):
        def __init__(self, waypoint: Waypoint) -> None: ...

    class Coordinate(SignificantPoint):
        def __init__(self, coordinate: Coordinate) -> None: ...

    @staticmethod
    def designator(value: str) -> SignificantPoint:
        """Parse a coded designator directly into a significant point."""

class FlightDuration:
    def __init__(self, total_minutes: int) -> None: ...
    @staticmethod
    def from_hours_minutes(hours: int, minutes: int) -> FlightDuration: ...
    @property
    def total_minutes(self) -> int: ...
    @property
    def hours(self) -> int: ...
    @property
    def minutes(self) -> int: ...
    @property
    def decimal_hours(self) -> str: ...

class AircraftType:
    def __init__(self, designator: str) -> None: ...
    @property
    def designator(self) -> str: ...

class AircraftRegistration:
    def __init__(self, nationality: str, registration: str) -> None: ...
    @property
    def nationality(self) -> str: ...
    @property
    def registration(self) -> str: ...

class Licence:
    def __init__(
        self, issuing_state: str, issuing_authority: str, number: str
    ) -> None: ...
    @property
    def issuing_state(self) -> str: ...
    @property
    def issuing_authority(self) -> str: ...
    @property
    def number(self) -> str: ...

class Aircraft:
    def __init__(
        self, aircraft_type: AircraftType, registration: AircraftRegistration
    ) -> None: ...
    @staticmethod
    def create(
        type_designator: str, nationality: str, registration: str
    ) -> Aircraft: ...
    @property
    def id(self) -> str: ...
    @property
    def aircraft_type(self) -> AircraftType: ...
    @property
    def registration(self) -> AircraftRegistration: ...

class Pilot:
    def __init__(
        self,
        display_name: str,
        legal_name: str | None = None,
        licences: list[Licence] | None = None,
        id: str | None = None,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def legal_name(self) -> str | None: ...
    @property
    def licences(self) -> list[Licence]: ...

class Flight:
    def __init__(
        self,
        aircraft_id: str,
        departure: SignificantPoint,
        arrival: SignificantPoint,
        first_movement: datetime | None = None,
        last_movement: datetime | None = None,
    ) -> None: ...
    @staticmethod
    def create(aircraft_id: str, departure: str, arrival: str) -> Flight:
        """Convenience constructor from coded designator strings, with no
        movement times recorded."""

    @property
    def id(self) -> str: ...
    @property
    def aircraft_id(self) -> str: ...
    @property
    def departure(self) -> SignificantPoint: ...
    @property
    def arrival(self) -> SignificantPoint: ...
    @property
    def first_movement(self) -> datetime | None: ...
    @property
    def last_movement(self) -> datetime | None: ...
    def route_summary(self) -> str: ...
    def duration(self) -> FlightDuration | None: ...
