"""Python bindings (PyO3) for the icao-shared-kernel Rust domain crate."""

from ._icao_shared_kernel import (
    Aircraft,
    AircraftRegistration,
    AircraftType,
    Coordinate,
    EmptyFieldError,
    FieldLengthError,
    Flight,
    FlightDuration,
    InvalidAircraftTypeError,
    IssuingStateError,
    LatitudeError,
    Licence,
    LongitudeError,
    Pilot,
    SignificantPoint,
    ValidationError,
    Waypoint,
    WaypointCharsetError,
    WaypointLengthError,
    validate_waypoint_code,
)

__all__ = [
    "Aircraft",
    "AircraftRegistration",
    "AircraftType",
    "Coordinate",
    "EmptyFieldError",
    "FieldLengthError",
    "Flight",
    "FlightDuration",
    "InvalidAircraftTypeError",
    "IssuingStateError",
    "LatitudeError",
    "Licence",
    "LongitudeError",
    "Pilot",
    "SignificantPoint",
    "ValidationError",
    "Waypoint",
    "WaypointCharsetError",
    "WaypointLengthError",
    "validate_waypoint_code",
]
